name: LeetCode Problem Scraper

on:
  schedule:
    - cron: '0 16 * * *'  # run every day at midnight
  workflow_dispatch: # manually trigger

jobs:
  scrape:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run script
      run:  |
        python scripts/daily_auto.py > /tmp/msg
        cat /tmp/msg

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        fi
        git commit -m "[$(TZ=Asia/Shanghai date +%Y%m%d)] Add daily LeetCode problem"

    - name: Push changes
      run: |
        if git log origin/master..HEAD --oneline | read; then
          git push
        else
          echo "No changes to push"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
